version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5433:5432'
    volumes:
      - type: bind
        source: E:/nest-hrm/db
        target: /var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres
    command:
      - 'postgres'
      - '-c'
      - 'track_commit_timestamp=on'
      - '-c'
      - 'log_destination=stderr'

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis

networks:
  postgres:
    driver: bridge
