version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - '5433:5432'
    volumes:
      - type: bind
        source: E:/nest-hrm/db
        target: /var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres
    command:
      - 'postgres'
      - '-c'
      - 'track_commit_timestamp=on'
      - '-c'
      - 'log_destination=stderr'
      
networks:
  postgres:
    driver: bridge